name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    uses: ./.github/workflows/ci.yml
  create-release:
    needs: [build-release]
    runs-on: ubuntu-20.04
    name: Create new release
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: compress artifacts
        working-directory: artifacts
        run: |
          mv pod-fluree-crypto-linux-amd64 pod-fluree-crypto && \
          zip pod-fluree-crypto-linux-amd64.zip pod-fluree-crypto && \
          rm pod-fluree-crypto
          mv pod-fluree-crypto-linux-arm64 pod-fluree-crypto && \
          zip pod-fluree-crypto-linux-arm64.zip pod-fluree-crypto && \
          rm pod-fluree-crypto
          mv pod-fluree-crypto-macos-amd64 pod-fluree-crypto && \
          zip pod-fluree-crypto-macos-amd64.zip pod-fluree-crypto && \
          rm pod-fluree-crypto
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.zip
