name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    id: build_release
    uses: ./.github/workflows/ci.yml
  create-release:
    needs: build_release
    runs-on: ubuntu-20.04
    name: Create new release
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: ls -R artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
