name: CD

on:
  push:
    branches:
      - main

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    name: Build for linux amd64 & arm64
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: network=host
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: localhost:5000/builder
      - name: Build linux/amd64 binary
        run: |
          docker run --platform=linux/amd64 -v ${{ github.workspace }}:/pod-fluree-crypto \
            localhost:5000/builder
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-linux-amd64
          path: ${{ github.workspace }}/pod-fluree-crypto
      - name: Build linux/arm64 binary
        run: |
          docker run --platform=linux/arm64 -v ${{ github.workspace }}:/pod-fluree-crypto \
            localhost:5000/builder
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-linux-arm64
          path: ${{ github.workspace }}/pod-fluree-crypto

  macos-build:
    runs-on: macos-11
    name: Build for macOS amd64
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 22.0.0.2
          java-version: 17
          components: native-image
          github-token: ${{ github.token }}
      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1075
      - name: build
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-macos-amd64
          path: ${{ github.workspace }}/pod-fluree-crypto
