name: CI

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  docker-builder:
    runs-on: ubuntu-20.04
    name: Build Docker builder image
    outputs:
      builder-image: ${{ steps.image-name.outputs.builder-image }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: network=host
      - name: Log in to registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - id: image-name
        run: |
          echo "::set-output name=builder-image::ghcr.io/${{ github.repository_owner }}/pod-fluree-crypto-builder:${{ github.sha }}"
      - uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-name.outputs.builder-image }}

  linux-build-arm64:
    needs: docker-builder
    runs-on: ubuntu-20.04
    name: Build for linux arm64
    steps:
    - name: Build linux/arm64 binary
      run: |
        docker run --platform=linux/arm64 --name=pfc-linux-arm64 \
          ${{ needs.docker-builder.outputs.builder-image }} make
        docker cp pfc-linux-arm64:/pod-fluree-crypto/pod-fluree-crypto \
          ${{ github.workspace }}/pod-fluree-crypto-linux-arm64
    - uses: actions/upload-artifact@v2
      with:
        name: pod-fluree-crypto-linux-arm64
        path: ${{ github.workspace }}/pod-fluree-crypto-linux-arm64

  linux-build-amd64:
    needs: docker-builder
    runs-on: ubuntu-20.04
    name: Build for linux amd64
    steps:
      - name: Build linux/amd64 binary
        run: |
          docker run --platform=linux/amd64 --name=pfc-linux-amd64 \
            ${{ needs.docker-builder.outputs.builder-image }} make
          docker cp pfc-linux-amd64:/pod-fluree-crypto/pod-fluree-crypto \
            ${{ github.workspace }}/pod-fluree-crypto-linux-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-linux-amd64
          path: ${{ github.workspace }}/pod-fluree-crypto-linux-amd64

  macos-build-amd64:
    runs-on: macos-11
    name: Build for macOS amd64
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 22.0.0.2
          java-version: 17
          components: native-image
          github-token: ${{ github.token }}
      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1075
      - name: build
        run: |
          make
          mv pod-fluree-crypto pod-fluree-crypto-macos-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-macos-amd64
          path: ${{ github.workspace }}/pod-fluree-crypto-macos-amd64
