name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+' # these will trigger this w/ workflow_call
  workflow_call:

jobs:
  linux-build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-20.04
    name: Build Linux binary
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch != 'amd64' }}
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build Linux builder image for ${{ matrix.arch }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          platforms: linux/${{ matrix.arch }}
          push: false
          load: true
          tags: builder
      - name: Build linux/${{ matrix.arch }} binary
        run: |
          docker run --platform=linux/${{ matrix.arch }} \
            --name=pfc-linux-${{ matrix.arch }} builder make
          docker cp pfc-linux-${{ matrix.arch }}:/pod-fluree-crypto/pod-fluree-crypto \
            ${{ github.workspace }}/pod-fluree-crypto-linux-${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/pod-fluree-crypto-linux-${{ matrix.arch }}

  macos-build-amd64:
    runs-on: macos-11
    name: Build macOS binary (amd64)
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 22.0.0.2
          java-version: 17
          components: native-image
          github-token: ${{ github.token }}
      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1075
      - name: build
        run: |
          make
          mv pod-fluree-crypto pod-fluree-crypto-macos-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: pod-fluree-crypto-macos-amd64
          path: ${{ github.workspace }}/pod-fluree-crypto-macos-amd64
